name: Docs
on:
  push:
    branches:
      - master

jobs:

  deploy:
    name: Docs
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:

    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
            export PATH="$PATH:/usr/lib/dart/bin";
            pub get
    - name: Build docs
      run: dartdoc

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: doc/api
