name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image:  andrewxhill/golang-dart-unstable:latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
            export PATH="$PATH:/usr/lib/dart/bin";
            pub get
    - name: Run tests
      run: |
           threadsd &
           export PATH=/usr/lib/dart/bin:$PATH;
           sleep 10; pub run test
